from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

@dataclass
class UserOrderContainer:
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Items: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

