from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

@dataclass
class UserOrderExecutionResult:
  Success: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Order: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Result: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ErrorMessage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ErrorCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

