<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class BacktestAPI
{
    private $connection;
    public BacktestAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns a list of accounts which can be used for backtesting goals
    /// </summary>
    /// <returns></returns>
    function GetBacktestAccounts()
    {
        return $connection->DoCall("BacktestAPI", "GET_BACKTEST_ACCOUNTS");
    }

    /// <summary>
    /// Does a debug run of the script
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="scripttype"></param>
    /// <param name="settings"></param>
    /// <returns></returns>
    function ExecuteDebugtest($scriptid,$scripttype,$settings)
    {
        return $connection->DoCall("BacktestAPI", "EXECUTE_DEBUGTEST", array(
        [
           "scriptid" = $scriptid,,
           "scripttype" = $scripttype,,
           "settings" = $settings,
        ];
    }

    /// <summary>
    /// Does a brief backtest
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="scriptid"></param>
    /// <param name="settings"></param>
    /// <returns></returns>
    function ExecuteQuicktest($backtestid,$scriptid,$settings)
    {
        return $connection->DoCall("BacktestAPI", "EXECUTE_QUICKTEST", array(
        [
           "backtestid" = $backtestid,,
           "scriptid" = $scriptid,,
           "settings" = $settings,
        ];
    }

    /// <summary>
    /// Executes a backtest
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="scriptid"></param>
    /// <param name="settings"></param>
    /// <param name="startunix"></param>
    /// <param name="endunix"></param>
    /// <returns></returns>
    function ExecuteBacktest($backtestid,$scriptid,$settings,$startunix,$endunix)
    {
        return $connection->DoCall("BacktestAPI", "EXECUTE_BACKTEST", array(
        [
           "backtestid" = $backtestid,,
           "scriptid" = $scriptid,,
           "settings" = $settings,,
           "startunix" = $startunix,,
           "endunix" = $endunix,
        ];
    }

    /// <summary>
    /// Cancels a running backtest
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="serviceid"></param>
    /// <returns></returns>
    function CancelBacktest($backtestid,$serviceid)
    {
        return $connection->DoCall("BacktestAPI", "CANCEL_BACKTEST", array(
        [
           "backtestid" = $backtestid,,
           "serviceid" = $serviceid,
        ];
    }

    /// <summary>
    /// Returns a list of all stored backtest results
    /// </summary>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetBacktestHistory($nextpageid,$pagelength)
    {
        return $connection->DoCall("BacktestAPI", "GET_BACKTEST_HISTORY", array(
        [
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }

    /// <summary>
    /// Returns the information of a backtest
    /// </summary>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestInfo($backtestid)
    {
        return $connection->DoCall("BacktestAPI", "GET_BACKTEST_INFO", array(
        [
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Returns the backtest execution log
    /// </summary>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestLogs($backtestid)
    {
        return $connection->DoCall("BacktestAPI", "GET_BACKTEST_LOGS", array(
        [
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Controls to archive a backtest result or not
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="archiveresult"></param>
    /// <returns></returns>
    function ArchiveBacktest($backtestid,$archiveresult)
    {
        return $connection->DoCall("BacktestAPI", "ARCHIVE_BACKTEST", array(
        [
           "backtestid" = $backtestid,,
           "archiveresult" = $archiveresult,
        ];
    }

    /// <summary>
    /// Changes a backtest tag
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="backtesttag"></param>
    /// <returns></returns>
    function EditBacktestTag($backtestid,$backtesttag)
    {
        return $connection->DoCall("BacktestAPI", "EDIT_BACKTEST_TAG", array(
        [
           "backtestid" = $backtestid,,
           "backtesttag" = $backtesttag,
        ];
    }

    /// <summary>
    /// Delete/remove a backtest result
    /// </summary>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function DeleteBacktest($backtestid)
    {
        return $connection->DoCall("BacktestAPI", "DELETE_BACKTEST", array(
        [
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Deletes/removes all unarchived backtest results
    /// </summary>
    /// <returns></returns>
    function DeleteUnarchivedBacktest()
    {
        return $connection->DoCall("BacktestAPI", "DELETE_UNARCHIVED_BACKTEST");
    }
}
