<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class CustomAPI
{
    private $connection;
    public CustomAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Gets all the default commands
    /// </summary>
    /// <param name="drivercode"></param>
    /// <param name="markettag"></param>
    /// <param name="orderbook"></param>
    /// <returns></returns>
    function GetDefaultCommands($drivercode,$markettag,$orderbook)
    {
        return $connection->DoCall("CustomAPI", "GET_DEFAULT_COMMANDS", array(
        [
           "drivercode" = $drivercode,,
           "markettag" = $markettag,,
           "orderbook" = $orderbook,
        ];
    }
}
