<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class SignalAPI
{
    private $connection;
    public SignalAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Use this webhook to send signals to the HaasCloud
    /// </summary>
    /// <param name="id"></param>
    /// <param name="secret"></param>
    /// <param name="signal"></param>
    /// <returns></returns>
    function StoreSignal($id,$secret,$signal)
    {
        return $connection->DoCall("SignalAPI", "STORE_SIGNAL", array(
        [
           "id" = $id,,
           "secret" = $secret,,
           "signal" = $signal,
        ];
    }

    /// <summary>
    /// This returns a list of all the user its signals
    /// </summary>
    /// <returns></returns>
    function MySignals()
    {
        return $connection->DoCall("SignalAPI", "MY_SIGNALS");
    }
}
