from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field

class UserOrder(BaseModel):
    """User order information matching autogenerated UserOrder"""
    unix: int = Field(alias="Unix")
    order_id: str = Field(alias="OrderId")
    stop_order_id: str = Field(alias="StopOrderId")
    market: str = Field(alias="CloudMarket")
    direction: str = Field(alias="Direction")
    type: str = Field(alias="Type")
    order_price: float = Field(alias="OrderPrice")
    trigger_price: float = Field(alias="TriggerPrice")
    order_amount: float = Field(alias="OrderAmount")
    trade_amount: float = Field(alias="TradeAmount")
    status: str = Field(alias="Status")
    bot_id: str = Field(alias="BotId")
    notes: str = Field(alias="Notes")

    class Config:
        populate_by_name = True

class RuntimeOrder(BaseModel):
    """Runtime order information matching autogenerated RuntimeOrder"""
    execution_count: int = Field(alias="ExecutionCount")

    class Config:
        populate_by_name = True

class RuntimeReport(BaseModel):
    """Bot runtime report matching autogenerated RuntimeReport"""
    account_id: str = Field(alias="AccountId")
    market: str = Field(alias="CloudMarket")
    amount_label: str = Field(alias="AmountLabel")
    margin_label: str = Field(alias="MarginLabel")
    profit_label: str = Field(alias="ProfitLabel")
    fees: Any = Field(alias="Fees")
    profits: Any = Field(alias="Profits")
    orders: List[RuntimeOrder] = Field(alias="Orders")
    positions: Any = Field(alias="Positions")
    performance: Any = Field(alias="Performance")

    class Config:
        populate_by_name = True

class AddBotFromLabRequest(BaseModel):
    """Request to create bot from lab"""
    lab_id: str
    backtest_id: str
    bot_name: str
    account_id: str
    market: str
    leverage: float = 1.0

class CreateBotRequest(BaseModel):
    """Request to create a new bot"""
    bot_name: str
    script_id: str
    script_type: str
    account_id: str
    market: str
    leverage: float = 1.0
    interval: int = 15
    chartstyle: int = 301

class HaasBot(BaseModel):
    """Main bot model matching autogenerated HaasBot"""
    user_id: str = Field(alias="UserId")
    bot_id: str = Field(alias="BotId")
    bot_name: str = Field(alias="BotName")
    script_id: str = Field(alias="ScriptId")
    script_version: str = Field(alias="ScriptVersion")
    account_id: str = Field(alias="AccountId")
    market: str = Field(alias="CloudMarket")
    execution_id: str = Field(alias="ExecutionId")
    is_activated: bool = Field(alias="IsActivated")
    is_paused: bool = Field(alias="IsPaused")
    is_favorite: bool = Field(alias="IsFavorite")
    notes: str = Field(alias="Notes")
    script_note: str = Field(alias="ScriptNote")
    notes_timestamp: int = Field(alias="NotesTimestamp")
    realized_profit: float = Field(alias="RealizedProfit")
    unrealized_profit: float = Field(alias="UnrealizedProfit")
    return_on_investment: float = Field(alias="ReturnOnInvestment")
    trade_amount_error: str = Field(alias="TradeAmountError")
    account_error: str = Field(alias="AccountError")
    script_error: str = Field(alias="ScriptError")
    update_counter: int = Field(alias="UpdateCounter")
    chart_interval: str = Field(alias="ChartInterval")
    chart_style: str = Field(alias="ChartStyle")
    chart_volume: bool = Field(alias="ChartVolume")
    runtime: Any = Field(alias="Runtime")
    script_package: Any = Field(alias="ScriptPackage")

    class Config:
        populate_by_name = True

class HaasBotAndRuntime(BaseModel):
    """Combined bot and runtime information"""
    bot: HaasBot = Field(alias="Bot")
    runtime: RuntimeReport = Field(alias="Runtime")

    class Config:
        populate_by_name = True

class Position(BaseModel):
    """Base position information"""
    position_id: str = Field(alias="PositionId")
    bot_id: str = Field(alias="BotId")
    market: str = Field(alias="CloudMarket")
    side: str = Field(alias="Side")
    entry_price: float = Field(alias="EntryPrice")
    amount: float = Field(alias="Amount")
    pnl: float = Field(alias="PnL")
    opened_at: int = Field(alias="OpenedAt")

    class Config:
        populate_by_name = True

class OpenPosition(Position):
    """Currently open position"""
    pass

class ClosedPosition(Position):
    """Closed position with exit information"""
    exit_price: float = Field(alias="ExitPrice")
    closed_at: int = Field(alias="ClosedAt")

# Export all models
__all__ = [
    'RuntimeReport',
    'AddBotFromLabRequest',
    'CreateBotRequest',
    'HaasBot',
    'HaasBotAndRuntime',
    'UserOrder',
    'RuntimeOrder',
    'Position',
    'OpenPosition',
    'ClosedPosition',
]
