from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumPlaceOrderResult(Enum):
  Open = 0
  Filled = 1
  InvalidMarket = 2
  InvalidAmount = 3
  InvalidTriggerPrice = 4
  BelowMinimumTradeAmount = 5
  BelowMinimumTradeVolume = 6
  PostOnly = 7
  ReduceOnly = 8
  InsufficientFunds = 9
  TradingEngineException = 10
  LeverageMismatch = 11
  KrakenFuturesDustOrderLimit = 12
  GoodTillCancel = 13
  FillOrKill = 14
  ImmediateOrCancel = 15
  Failed = 16

