from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumExchangeType(Enum):
  Spot = 0
  Margin = 1
  Leverage = 2

