from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasOrderTriggerPrice(Enum):
  LastPrice = 0
  MarkPrice = 1
  IndexPrice = 2

