from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasUserDataType(Enum):
  None = 0
  HaasNumberCollection = 1
  HaasCallback = 2
  HaasEnum = 3
  HaasResultContainer = 4
  HaasColor = 5
  HaasSignal = 6

