from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasScriptType(Enum):
  Lua = 0
  Visual = 1
  TradeBot = 2

