from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumLoginResult(Enum):
  Success = 0
  InvalidUsernameOrPassword = 1
  Invalid2FACode = 2
  UnknownDevice = 3
  Failed = 4
  TwoFANeeded = 5
  Blocked = 6
  NotAllowed = 7
  Unapproved = -1

