from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumRelationType(Enum):
  None = 0
  Bronze = 1
  Silver = 2
  Golden = 3

