from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumCloudMarketContractType(Enum):
  Vanilla = 0
  Inverse = 1
  Quanto = 2

