from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumUserLabAlgorithm(Enum):
  BruteForce = 0
  Intelligent = 1
  Random = 2
  Cluster = 3

