from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasOrderType(Enum):
  Limit = 0
  Market = 1
  StopLimit = 2
  StopMarket = 3
  TakeProfitLimit = 4
  TakeProfitMarket = 5
  TrailingStopLimit = 6
  TrailingStopMarket = 7

