from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumUserLabStatus(Enum):
  Created = 0
  Queued = 1
  Running = 2
  Completed = 3
  Cancelled = 4

