<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class AccountAPI
{
    private $connection;
    public AccountAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns a list of all real and simulated accounts
    /// </summary>
    /// <returns></returns>
    function GetAccounts()
    {
        return $connection->DoCall("AccountAPI", "GET_ACCOUNTS");
    }

    /// <summary>
    /// Returns all the details of the given account (wallet, orders, positions)
    /// </summary>
    /// <param name="accountid"></param>
    /// <returns></returns>
    function GetAccountData($accountid)
    {
        return $connection->DoCall("AccountAPI", "GET_ACCOUNT_DATA", array(
        [
           "accountid" = $accountid,
        ];
    }

    /// <summary>
    /// Returns the wallet of the given account
    /// </summary>
    /// <param name="accountid"></param>
    /// <returns></returns>
    function GetBalance($accountid)
    {
        return $connection->DoCall("AccountAPI", "GET_BALANCE", array(
        [
           "accountid" = $accountid,
        ];
    }

    /// <summary>
    /// Returns all the user its wallets of all accounts
    /// </summary>
    /// <returns></returns>
    function GetAllBalances()
    {
        return $connection->DoCall("AccountAPI", "GET_ALL_BALANCES");
    }

    /// <summary>
    /// Returns the open orders of the given account
    /// </summary>
    /// <param name="accountid"></param>
    /// <returns></returns>
    function GetOrders($accountid)
    {
        return $connection->DoCall("AccountAPI", "GET_ORDERS", array(
        [
           "accountid" = $accountid,
        ];
    }

    /// <summary>
    /// Returns all the user its open orders of all accounts
    /// </summary>
    /// <returns></returns>
    function GetAllOrders()
    {
        return $connection->DoCall("AccountAPI", "GET_ALL_ORDERS");
    }

    /// <summary>
    /// Returns the open positions of the given account
    /// </summary>
    /// <param name="accountid"></param>
    /// <returns></returns>
    function GetPositions($accountid)
    {
        return $connection->DoCall("AccountAPI", "GET_POSITIONS", array(
        [
           "accountid" = $accountid,
        ];
    }

    /// <summary>
    /// Returns all the user its open positions of all accounts
    /// </summary>
    /// <returns></returns>
    function GetAllPositions()
    {
        return $connection->DoCall("AccountAPI", "GET_ALL_POSITIONS");
    }

    /// <summary>
    /// Returns the historical trades of the given account
    /// </summary>
    /// <param name="accountids"></param>
    /// <param name="marketsearchtags"></param>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetTrades($accountids,$marketsearchtags,$nextpageid,$pagelength)
    {
        return $connection->DoCall("AccountAPI", "GET_TRADES", array(
        [
           "accountids" = $accountids,,
           "marketsearchtags" = $marketsearchtags,,
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }

    /// <summary>
    /// Returns the leverage settings as setup on the API (per market)
    /// </summary>
    /// <param name="accountid"></param>
    /// <returns></returns>
    function GetPositionMode($accountid)
    {
        return $connection->DoCall("AccountAPI", "GET_POSITION_MODE", array(
        [
           "accountid" = $accountid,
        ];
    }

    /// <summary>
    /// Returns the leverage settings as setup on the API (per market)
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function GetMarginSettings($accountid,$market)
    {
        return $connection->DoCall("AccountAPI", "GET_MARGIN_SETTINGS", array(
        [
           "accountid" = $accountid,,
           "market" = $market,
        ];
    }

    /// <summary>
    /// Deposits funds from a simulated account
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="walletid"></param>
    /// <param name="currency"></param>
    /// <param name="amount"></param>
    /// <returns></returns>
    function DepositFunds($accountid,$walletid,$currency,$amount)
    {
        return $connection->DoCall("AccountAPI", "DEPOSIT_FUNDS", array(
        [
           "accountid" = $accountid,,
           "walletid" = $walletid,,
           "currency" = $currency,,
           "amount" = $amount,
        ];
    }

    /// <summary>
    /// Withdrawals funds from a simulated account
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="walletid"></param>
    /// <param name="currency"></param>
    /// <param name="amount"></param>
    /// <returns></returns>
    function WithdrawalFunds($accountid,$walletid,$currency,$amount)
    {
        return $connection->DoCall("AccountAPI", "WITHDRAWAL_FUNDS", array(
        [
           "accountid" = $accountid,,
           "walletid" = $walletid,,
           "currency" = $currency,,
           "amount" = $amount,
        ];
    }
}
