<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class BotAPI
{
    private $connection;
    public BotAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the requested bot
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function GetBot($botid)
    {
        return $connection->DoCall("BotAPI", "GET_BOT", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Returns all the user its bots
    /// </summary>
    /// <returns></returns>
    function GetBots()
    {
        return $connection->DoCall("BotAPI", "GET_BOTS");
    }

    /// <summary>
    /// Returns the bot report
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function GetRuntimeReport($botid)
    {
        return $connection->DoCall("BotAPI", "GET_RUNTIME_REPORT", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Returns the bots archived positions
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function GetRuntimeOpenOrders($botid)
    {
        return $connection->DoCall("BotAPI", "GET_RUNTIME_OPEN_ORDERS", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Returns the bots archived positions
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function GetRuntimeOpenPositions($botid)
    {
        return $connection->DoCall("BotAPI", "GET_RUNTIME_OPEN_POSITIONS", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Returns the bots archived positions
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetRuntimeClosedPositions($botid,$nextpageid,$pagelength)
    {
        return $connection->DoCall("BotAPI", "GET_RUNTIME_CLOSED_POSITIONS", array(
        [
           "botid" = $botid,,
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }

    /// <summary>
    /// Activates the given bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="cleanreports"></param>
    /// <returns></returns>
    function ActivateBot($botid,$cleanreports)
    {
        return $connection->DoCall("BotAPI", "ACTIVATE_BOT", array(
        [
           "botid" = $botid,,
           "cleanreports" = $cleanreports,
        ];
    }

    /// <summary>
    /// Deactivates the given bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="cancelorders"></param>
    /// <returns></returns>
    function DeactivateBot($botid,$cancelorders)
    {
        return $connection->DoCall("BotAPI", "DEACTIVATE_BOT", array(
        [
           "botid" = $botid,,
           "cancelorders" = $cancelorders,
        ];
    }

    /// <summary>
    /// Activates the given bot
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function PauseBot($botid)
    {
        return $connection->DoCall("BotAPI", "PAUSE_BOT", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Deactivates the given bot
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function ResumeBot($botid)
    {
        return $connection->DoCall("BotAPI", "RESUME_BOT", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Deactivates all bots, the accountId and market are optional
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function DeactivateAllBots($accountid,$market)
    {
        return $connection->DoCall("BotAPI", "DEACTIVATE_ALL_BOTS", array(
        [
           "accountid" = $accountid,,
           "market" = $market,
        ];
    }

    /// <summary>
    /// Add a new bot
    /// </summary>
    /// <param name="botname"></param>
    /// <param name="scriptid"></param>
    /// <param name="scripttype"></param>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="leverage"></param>
    /// <param name="interval"></param>
    /// <param name="chartstyle"></param>
    /// <returns></returns>
    function AddBot($botname,$scriptid,$scripttype,$accountid,$market,$leverage,$interval,$chartstyle)
    {
        return $connection->DoCall("BotAPI", "ADD_BOT", array(
        [
           "botname" = $botname,,
           "scriptid" = $scriptid,,
           "scripttype" = $scripttype,,
           "accountid" = $accountid,,
           "market" = $market,,
           "leverage" = $leverage,,
           "interval" = $interval,,
           "chartstyle" = $chartstyle,
        ];
    }

    /// <summary>
    /// Add a new bot from a backtest result
    /// </summary>
    /// <param name="backtestid"></param>
    /// <param name="botname"></param>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function AddBotFromBacktest($backtestid,$botname,$accountid,$market)
    {
        return $connection->DoCall("BotAPI", "ADD_BOT_FROM_BACKTEST", array(
        [
           "backtestid" = $backtestid,,
           "botname" = $botname,,
           "accountid" = $accountid,,
           "market" = $market,
        ];
    }

    /// <summary>
    /// Add a new bot from a backtest result
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="backtestid"></param>
    /// <param name="botname"></param>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function AddBotFromLabs($labid,$backtestid,$botname,$accountid,$market)
    {
        return $connection->DoCall("BotAPI", "ADD_BOT_FROM_LABS", array(
        [
           "labid" = $labid,,
           "backtestid" = $backtestid,,
           "botname" = $botname,,
           "accountid" = $accountid,,
           "market" = $market,
        ];
    }

    /// <summary>
    /// Edits the bots its settings
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="settings"></param>
    /// <returns></returns>
    function EditSettings($botid,$settings)
    {
        return $connection->DoCall("BotAPI", "EDIT_SETTINGS", array(
        [
           "botid" = $botid,,
           "settings" = $settings,
        ];
    }

    /// <summary>
    /// Edits the bots its script
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="scriptid"></param>
    /// <param name="scripttype"></param>
    /// <returns></returns>
    function EditScript($botid,$scriptid,$scripttype)
    {
        return $connection->DoCall("BotAPI", "EDIT_SCRIPT", array(
        [
           "botid" = $botid,,
           "scriptid" = $scriptid,,
           "scripttype" = $scripttype,
        ];
    }

    /// <summary>
    /// Renames the bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="botname"></param>
    /// <returns></returns>
    function RenameBot($botid,$botname)
    {
        return $connection->DoCall("BotAPI", "RENAME_BOT", array(
        [
           "botid" = $botid,,
           "botname" = $botname,
        ];
    }

    /// <summary>
    /// Changes the notes of/in the bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="notes"></param>
    /// <returns></returns>
    function ChangeBotNotes($botid,$notes)
    {
        return $connection->DoCall("BotAPI", "CHANGE_BOT_NOTES", array(
        [
           "botid" = $botid,,
           "notes" = $notes,
        ];
    }

    /// <summary>
    /// Makes a bot a favorite bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="isfavorite"></param>
    /// <returns></returns>
    function FavoriteBot($botid,$isfavorite)
    {
        return $connection->DoCall("BotAPI", "FAVORITE_BOT", array(
        [
           "botid" = $botid,,
           "isfavorite" = $isfavorite,
        ];
    }

    /// <summary>
    /// Clones a excisting bot
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="botname"></param>
    /// <returns></returns>
    function CloneBot($botid,$botname)
    {
        return $connection->DoCall("BotAPI", "CLONE_BOT", array(
        [
           "botid" = $botid,,
           "botname" = $botname,
        ];
    }

    /// <summary>
    /// Cleans the bot its logbook and trades
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="config"></param>
    /// <returns></returns>
    function ResetBot($botid,$config)
    {
        return $connection->DoCall("BotAPI", "RESET_BOT", array(
        [
           "botid" = $botid,,
           "config" = $config,
        ];
    }

    /// <summary>
    /// Deletes/removes the given bot
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function DeleteBot($botid)
    {
        return $connection->DoCall("BotAPI", "DELETE_BOT", array(
        [
           "botid" = $botid,
        ];
    }

    /// <summary>
    /// Returns all the open bot orders
    /// </summary>
    /// <returns></returns>
    function GetOpenOrders()
    {
        return $connection->DoCall("BotAPI", "GET_OPEN_ORDERS");
    }

    /// <summary>
    /// Returns all the open bot positions
    /// </summary>
    /// <returns></returns>
    function GetOpenPositions()
    {
        return $connection->DoCall("BotAPI", "GET_OPEN_POSITIONS");
    }

    /// <summary>
    /// Cancels a bot order (manually)
    /// </summary>
    /// <param name="botid"></param>
    /// <param name="orderid"></param>
    /// <returns></returns>
    function CancelOrder($botid,$orderid)
    {
        return $connection->DoCall("BotAPI", "CANCEL_ORDER", array(
        [
           "botid" = $botid,,
           "orderid" = $orderid,
        ];
    }

    /// <summary>
    /// Cancels all bot orders (manually)
    /// </summary>
    /// <param name="botid"></param>
    /// <returns></returns>
    function CancelAllOrders($botid)
    {
        return $connection->DoCall("BotAPI", "CANCEL_ALL_ORDERS", array(
        [
           "botid" = $botid,
        ];
    }
}
