<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class HaasScriptAPI
{
    private $connection;
    public HaasScriptAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetCommands()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_COMMANDS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetBlocks()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BLOCKS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetCommand($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_COMMAND", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetBlock($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BLOCK", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetScriptItem($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_ITEM", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetAllScriptItems()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_ALL_SCRIPT_ITEMS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetScriptRecord($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_RECORD", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetAllScriptRecords()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_ALL_SCRIPT_RECORDS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <param name="script"></param>
    /// <param name="type"></param>
    /// <returns></returns>
    function AddScript($name,$description,$script,$type)
    {
        return $connection->DoCall("HaasScriptAPI", "ADD_SCRIPT", array(
        [
           "name" = $name,,
           "description" = $description,,
           "script" = $script,,
           "type" = $type,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <param name="script"></param>
    /// <returns></returns>
    function EditScript($scriptid,$name,$description,$script)
    {
        return $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT", array(
        [
           "scriptid" = $scriptid,,
           "name" = $name,,
           "description" = $description,,
           "script" = $script,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <returns></returns>
    function EditScriptSpecifications($scriptid,$name,$description)
    {
        return $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_SPECIFICATIONS", array(
        [
           "scriptid" = $scriptid,,
           "name" = $name,,
           "description" = $description,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="sourcecode"></param>
    /// <param name="settings"></param>
    /// <returns></returns>
    function EditScriptSourcecode($scriptid,$sourcecode,$settings)
    {
        return $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_SOURCECODE", array(
        [
           "scriptid" = $scriptid,,
           "sourcecode" = $sourcecode,,
           "settings" = $settings,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function DeleteScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "DELETE_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function PublishScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "PUBLISH_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function PublishCommunityScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "PUBLISH_COMMUNITY_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function UnpublishScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "UNPUBLISH_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetProfiles()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_PROFILES");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetProfile($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_PROFILE", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Returns a list of the backup versions
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetBackupVersions($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BACKUP_VERSIONS", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Creates a backup of the given script
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function CreateNewBackup($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "CREATE_NEW_BACKUP", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Restores a backup
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="wantedversion"></param>
    /// <returns></returns>
    function RestoreBackup($scriptid,$wantedversion)
    {
        return $connection->DoCall("HaasScriptAPI", "RESTORE_BACKUP", array(
        [
           "scriptid" = $scriptid,,
           "wantedversion" = $wantedversion,
        ];
    }

    /// <summary>
    /// Opens the backup file as new script
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="wantedversion"></param>
    /// <returns></returns>
    function GetBackup($scriptid,$wantedversion)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BACKUP", array(
        [
           "scriptid" = $scriptid,,
           "wantedversion" = $wantedversion,
        ];
    }

    /// <summary>
    /// Searches to find code within the scripts
    /// </summary>
    /// <param name="searchkey"></param>
    /// <returns></returns>
    function SearchInScripts($searchkey)
    {
        return $connection->DoCall("HaasScriptAPI", "SEARCH_IN_SCRIPTS", array(
        [
           "searchkey" = $searchkey,
        ];
    }
}
