<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class InterfaceAPI
{
    private $connection;
    public InterfaceAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the market information page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_INFO", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the market price information page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketPriceInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_PRICE_INFO", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the market price technical analysis page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketTaInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_TA_INFO", array(
        [
           "market" = $market,
        ];
    }
}
