<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class LabsAPI
{
    private $connection;
    public LabsAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the saved labs records
    /// </summary>
    /// <returns></returns>
    function GetLabs()
    {
        return $connection->DoCall("LabsAPI", "GET_LABS");
    }

    /// <summary>
    /// Creates a new lab record
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="name"></param>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="interval"></param>
    /// <param name="style"></param>
    /// <returns></returns>
    function CreateLab($scriptid,$name,$accountid,$market,$interval,$style)
    {
        return $connection->DoCall("LabsAPI", "CREATE_LAB", array(
        [
           "scriptid" = $scriptid,,
           "name" = $name,,
           "accountid" = $accountid,,
           "market" = $market,,
           "interval" = $interval,,
           "style" = $style,
        ];
    }

    /// <summary>
    /// Clones a existing lab record
    /// </summary>
    /// <param name="labid"></param>
    /// <returns></returns>
    function CloneLab($labid)
    {
        return $connection->DoCall("LabsAPI", "CLONE_LAB", array(
        [
           "labid" = $labid,
        ];
    }

    /// <summary>
    /// Returns the details of a specific lab record
    /// </summary>
    /// <param name="labid"></param>
    /// <returns></returns>
    function DeleteLab($labid)
    {
        return $connection->DoCall("LabsAPI", "DELETE_LAB", array(
        [
           "labid" = $labid,
        ];
    }

    /// <summary>
    /// Returns the details of a specific lab record
    /// </summary>
    /// <param name="labid"></param>
    /// <returns></returns>
    function GetLabDetails($labid)
    {
        return $connection->DoCall("LabsAPI", "GET_LAB_DETAILS", array(
        [
           "labid" = $labid,
        ];
    }

    /// <summary>
    /// Changes the script of the lab record
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function ChangeLabScript($labid,$scriptid)
    {
        return $connection->DoCall("LabsAPI", "CHANGE_LAB_SCRIPT", array(
        [
           "labid" = $labid,,
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Updates the labs configuration.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="name"></param>
    /// <param name="type"></param>
    /// <param name="config"></param>
    /// <param name="settings"></param>
    /// <param name="parameters"></param>
    /// <returns></returns>
    function UpdateLabDetails($labid,$name,$type,$config,$settings,$parameters)
    {
        return $connection->DoCall("LabsAPI", "UPDATE_LAB_DETAILS", array(
        [
           "labid" = $labid,,
           "name" = $name,,
           "type" = $type,,
           "config" = $config,,
           "settings" = $settings,,
           "parameters" = $parameters,
        ];
    }

    /// <summary>
    /// Updates the labs configuration.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="startunix"></param>
    /// <param name="endunix"></param>
    /// <returns></returns>
    function StartLabExecution($labid,$startunix,$endunix)
    {
        return $connection->DoCall("LabsAPI", "START_LAB_EXECUTION", array(
        [
           "labid" = $labid,,
           "startunix" = $startunix,,
           "endunix" = $endunix,
        ];
    }

    /// <summary>
    /// Updates the labs configuration.
    /// </summary>
    /// <param name="labid"></param>
    /// <returns></returns>
    function CancelLabExecution($labid)
    {
        return $connection->DoCall("LabsAPI", "CANCEL_LAB_EXECUTION", array(
        [
           "labid" = $labid,
        ];
    }

    /// <summary>
    /// Updates the labs configuration.
    /// </summary>
    /// <param name="labid"></param>
    /// <returns></returns>
    function GetLabExecutionUpdate($labid)
    {
        return $connection->DoCall("LabsAPI", "GET_LAB_EXECUTION_UPDATE", array(
        [
           "labid" = $labid,
        ];
    }

    /// <summary>
    /// Get labs result.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestResult($labid,$backtestid)
    {
        return $connection->DoCall("LabsAPI", "GET_BACKTEST_RESULT", array(
        [
           "labid" = $labid,,
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Get labs results.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetBacktestResultPage($labid,$nextpageid,$pagelength)
    {
        return $connection->DoCall("LabsAPI", "GET_BACKTEST_RESULT_PAGE", array(
        [
           "labid" = $labid,,
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }

    /// <summary>
    /// Get labs result.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestRuntime($labid,$backtestid)
    {
        return $connection->DoCall("LabsAPI", "GET_BACKTEST_RUNTIME", array(
        [
           "labid" = $labid,,
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Get labs result.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestChart($labid,$backtestid)
    {
        return $connection->DoCall("LabsAPI", "GET_BACKTEST_CHART", array(
        [
           "labid" = $labid,,
           "backtestid" = $backtestid,
        ];
    }

    /// <summary>
    /// Get labs result.
    /// </summary>
    /// <param name="labid"></param>
    /// <param name="backtestid"></param>
    /// <returns></returns>
    function GetBacktestLog($labid,$backtestid)
    {
        return $connection->DoCall("LabsAPI", "GET_BACKTEST_LOG", array(
        [
           "labid" = $labid,,
           "backtestid" = $backtestid,
        ];
    }
}
