<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class PortfolioAPI
{
    private $connection;
    public PortfolioAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the wallet and total balance
    /// </summary>
    /// <param name="pricesource">Name of the pricesource, like BINANCE</param>
    /// <param name="fromcurrency"></param>
    /// <param name="tocurrency"></param>
    /// <param name="amount"></param>
    /// <returns></returns>
    function Convert($pricesource,$fromcurrency,$tocurrency,$amount)
    {
        return $connection->DoCall("PortfolioAPI", "CONVERT", array(
        [
           "pricesource" = $pricesource,,
           "fromcurrency" = $fromcurrency,,
           "tocurrency" = $tocurrency,,
           "amount" = $amount,
        ];
    }

    /// <summary>
    /// Returns the balance mutation per user
    /// </summary>
    /// <param name="accountids"></param>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetBalanceMutations($accountids,$nextpageid,$pagelength)
    {
        return $connection->DoCall("PortfolioAPI", "GET_BALANCE_MUTATIONS", array(
        [
           "accountids" = $accountids,,
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }
}
