<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class TradingAPI
{
    private $connection;
    public TradingAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Places a order
    /// </summary>
    /// <param name="order"></param>
    /// <returns></returns>
    function PlaceOrder($order)
    {
        return $connection->DoCall("TradingAPI", "PLACE_ORDER", array(
        [
           "order" = $order,
        ];
    }

    /// <summary>
    /// Cancels a open order
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="orderid"></param>
    /// <returns></returns>
    function CancelOrder($accountid,$orderid)
    {
        return $connection->DoCall("TradingAPI", "CANCEL_ORDER", array(
        [
           "accountid" = $accountid,,
           "orderid" = $orderid,
        ];
    }

    /// <summary>
    /// Returns what the used margin is
    /// </summary>
    /// <param name="drivername"></param>
    /// <param name="drivertype"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="leverage"></param>
    /// <param name="price"></param>
    /// <param name="amount"></param>
    /// <returns></returns>
    function UsedMargin($drivername,$drivertype,$market,$leverage,$price,$amount)
    {
        return $connection->DoCall("TradingAPI", "USED_MARGIN", array(
        [
           "drivername" = $drivername,,
           "drivertype" = $drivertype,,
           "market" = $market,,
           "leverage" = $leverage,,
           "price" = $price,,
           "amount" = $amount,
        ];
    }

    /// <summary>
    /// Calculates the maximum trade amount, price and margin
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="price"></param>
    /// <param name="usedamount"></param>
    /// <param name="amountpercentage"></param>
    /// <param name="isbuy"></param>
    /// <returns></returns>
    function MaxAmount($accountid,$market,$price,$usedamount,$amountpercentage,$isbuy)
    {
        return $connection->DoCall("TradingAPI", "MAX_AMOUNT", array(
        [
           "accountid" = $accountid,,
           "market" = $market,,
           "price" = $price,,
           "usedamount" = $usedamount,,
           "amountpercentage" = $amountpercentage,,
           "isbuy" = $isbuy,
        ];
    }

    /// <summary>
    /// Cancels all open orders open order, accountid and market as optional
    /// </summary>
    /// <param name="accountid"></param>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function CancelAllOpenOrders($accountid,$market)
    {
        return $connection->DoCall("TradingAPI", "CANCEL_ALL_OPEN_ORDERS", array(
        [
           "accountid" = $accountid,,
           "market" = $market,
        ];
    }
}
