<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class UserAPI
{
    private $connection;
    public UserAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// The 3th party login
    /// </summary>
    /// <param name="email"></param>
    /// <param name="secretkey"></param>
    /// <returns></returns>
    function AppLogin($email,$secretkey)
    {
        return $connection->DoCall("UserAPI", "APP_LOGIN", array(
        [
           "email" = $email,,
           "secretkey" = $secretkey,
        ];
    }

    /// <summary>
    /// This checks if the user login is still valid
    /// </summary>
    /// <returns></returns>
    function CheckToken()
    {
        return $connection->DoCall("UserAPI", "CHECK_TOKEN");
    }

    /// <summary>
    /// Logout procedure
    /// </summary>
    /// <returns></returns>
    function Logout()
    {
        return $connection->DoCall("UserAPI", "LOGOUT");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="deviceid"></param>
    /// <returns></returns>
    function IsDeviceApproved($deviceid)
    {
        $connection->DoCall("UserAPI", "IS_DEVICE_APPROVED", array(
        [
           "deviceid" = $deviceid,
        ];
    }
}
