from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasChartLineType(Enum):
  Line = 0
  Bars = 1
  Band = 2
  Circle = 3
  Cloud = 4
  DoubleColor = 5
  DoubleColorFill = 6
  Histogram = 7
  StackedArea = 9
  Volume = 10
  SignalBars = 11
  PricePlotVolume = 13

