from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasChartLineStyle(Enum):
  Smooth = 700
  Spiked = 701
  Step = 702
  StepAfter = 703
  StepBefore = 704

