from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasOrderDirection(Enum):
  Buy = 0
  Sell = 1
  GoLong = 2
  ExitLong = 3
  GoShort = 4
  ExitShort = 5

