from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasOrderStatus(Enum):
  Unknown = 0
  Open = 1
  Completed = 2
  Cancelled = 3
  Pending = -2
  Failed = -1

