from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasInputFieldType(Enum):
  Number = 0
  Text = 1
  Checkbox = 2
  Dropdown = 3
  PriceSource = 4
  PriceSourceMarket = 5
  Account = 6
  AccountMarket = 7
  CloudMarket = 8
  Interval = 9
  Header = 10
  Table = 11
  Button = 12
  OrderType = 90
  ChartStyle = 91

