from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasCommandParameterType(Enum):
  String = 0
  Number = 1
  Enum = 2
  Boolean = 3
  Dynamic = 4
  NumberOrTable = 6
  ListNumbers = 7
  ListDynamic = 8
  Function = 9
  Void = 10
  Connector = 11
  DynamicParams = 100
  EnumParams = 101
  BooleanParams = 102
  StringParams = 103
  NumberParams = 104
  ListNumberParams = 105
  NumberOrTableParams = 106

