from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasScriptOrderType(Enum):
  Limit = 500
  CloudMarket = 501
  NoTimeout = 502
  MakerOrCancel = 503
  StopLimit = 504
  StopMarket = 505
  TakeProfitLimit = 506
  TakeProfitMarket = 507
  TrailingStopMarket = 508
  Default = -1

