from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasChartShapeType(Enum):
  Cross = 1600
  Add = 1601
  Circle = 1602
  TriangleUp = 1603
  TriangleDown = 1604
  Square = 1605
  Diamond = 1606
  Text = 1607

