from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasChartStatus(Enum):
  IsPerfect = 0
  IsEmpty = 1
  IsBroken = 2
  CompileError = 3
  IsRunning = 4
  IsLimit = 5

