from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasCommandSyntaxType(Enum):
  Function = 1
  Enum = 15
  Color = 19

