from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumUserRights(Enum):
  Trial = 0
  Version3User = 1
  EnterpriseDeveloper = 2
  EnterpriseBeginner = 3
  EnterpriseSimple = 4
  EnterpriseAdvanced = 5
  SponsoredByExchange = 9
  Dashboard = 11
  Beginner = 12
  Simple = 13
  Advanced = 14
  Partner = 50
  Administrator = 51
  Developer = 52
  Unapproved = -1

