from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumUserBalanceMutation(Enum):
  Deposit = 0
  Withdrawal = 1
  Transfer = 2

