from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

class EnumHaasScriptMarketType(Enum):
  Spot = 1500
  Margin = 1501
  Leverage = 1502

