from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

@dataclass
class HaasScriptCompileRecord:
  IsValid: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Command: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandNameReferences: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CompileLog: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LuaCompileError: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  VisualCompileError: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Inputs: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DefaultTemplate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HideTradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HideOrderTemplate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSpotSupported: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsMarginSupported: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsLeverageSupported: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsManagedTrading: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsOneDirection: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsMultiMarket: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsRemoteSignalBased: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsTAUsed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

