from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

@dataclass
class HaasChartPricePlotColorScheme:
  Up: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Down: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DownFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Marked: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarkedFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

