from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.6.3
// Production date: 20-12-2021
// </summary>

@dataclass
class HaasScriptSettings:
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PositionMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Leverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Interval: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ChartStyle: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderTemplate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptParameters: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

