import dataclasses
from typing import Any, List

@dataclasses.dataclass
class HaasScriptRuntime:
    CompilerErrors: List[Any]
    MainExecutor: Any
    ExecutionStack: List[Any]
    CurrentExecutor: Any
    CurrentTradeSignal: Any
    Reports: Any
    CustomReport: Any
    ScriptNote: str
    OpenOrders: List[Any]
    FailedOrders: List[Any]
    OrderExecutionRequests: List[Any]
    OrderCancelRequests: List[Any]
    FinishedOrdersIds: List[str]
    FinishedPositionIds: List[str]
    ManagedLongPosition: Any
    ManagedShortPosition: Any
    UnmanagedPositions: List[Any]
    DatabasePositions: List[Any]
    FinishedPositions: List[Any]
    CachedPositions: List[Any]
    SplitOrderCount: int
    InputFields: List[Any]
    ScriptMemory: Any
    LocalMemory: Any
    RedisKeys: List[Any]
    SessionMemory: Any
    ButtonMemory: Any
    LogId: str
    LogCount: int
    ExecutionLog: List[Any]
    ExecutionToken: Any
    ScriptType: str
    IsCommandScript: bool
    UserId: str
    BotId: str
    BotName: str
    ScriptId: str
    ScriptName: str
    Activated: bool
    Paused: bool
    ActivatedSince: int
    DeactivatedSince: int
    AccountId: str
    AccountIds: List[str]
    PriceMarket: str
    BotMarketType: str
    Leverage: float
    MarginMode: str
    PositionMode: str
    TradeAmount: float
    OrderTemplate: Any
    DefaultInterval: str
    DefaultChartType: str
    HideTradeAmountSettings: bool
    HideOrderSettings: bool
    OrderPersistenceEnabled: bool
    OrderPersistenceLimit: int
    EnableHighSpeedUpdates: bool
    UpdateAfterCompletedOrder: bool
    IndicatorContainerLogs: List[Any]
    IsDoingInit: bool
    IsDoingDebug: bool
    IsDoingBacktest: bool
    IsDoingBacktestFinalize: bool
    IsDoingLabsBacktests: bool
    IsScriptOk: bool
    TradeAmountError: str
    ScriptTradeAmountError: str
    UpdateCounter: int
    IsSpotSupported: bool
    IsMarginSupported: bool
    IsLeverageSupported: bool
    IsManagedTrading: bool
    IsOneDirection: bool
    IsMultiMarket: bool
    IsRemoteSignalBased: bool
    IsTAUsed: bool
    Timestamp: int
    MinuteTimestamp: int
    LastUpdateTimestamp: int
    BacktestStartUnix: int
    BacktestEndUnix: int
